# Generated by Django 4.2.14 on 2025-04-13 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0001_initial"),
        ("officers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="officerrating",
            name="complaint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="complaints.complaint",
                unique=True,
            ),
        ),
    ]
